In [5]:
%matplotlib inline
import numpy as np
import matplotlib.pyplot as plt
A = np.array ([[1,2,3], [4,5,6], [7,8,9]])
B = np.array ([2,5,11])
Q,R =np.linalg.qr(A)
print (A)
print (Q)
print (R)
R1 = R [:2,:2]
R1
B1= np.dot(np.transpose(Q),B)[:2]
B1
X1 = np.linalg.solve(R1,B1)
X1

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[-0.12309149  0.90453403  0.40824829]
 [-0.49236596  0.30151134 -0.81649658]
 [-0.86164044 -0.30151134  0.40824829]]
[[ -8.1240384   -9.6011363  -11.07823419]
 [  0.           0.90453403   1.80906807]
 [  0.           0.           0.        ]]


array([1.50000000e+00, 1.47287728e-15])