In [21]:
%matplotlib inline
import scipy.linalg as linalg
import numpy as np

A = np.array ([[1,2,3], [2,16,21],[4,28,73]])

P,L,U = scipy.linalg.lu(A)
print (P)
print (L)
print (U)
print (np.dot(P,A)-np.dot(L,U))
B = np.array ([4,6,3])
C = np.linalg.solve(L,B)
print (C)
D = np.linalg.solve(U,C)
print (D)


[[0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]]
[[ 1.    0.    0.  ]
 [ 0.25  1.    0.  ]
 [ 0.5  -0.4   1.  ]]
[[  4.    28.    73.  ]
 [  0.    -5.   -15.25]
 [  0.     0.   -21.6 ]]
[[ -2. -12. -52.]
 [  3.  26.  70.]
 [ -1. -14. -18.]]
[4. 5. 3.]
[ 7.56944444 -0.57638889 -0.13888889]
