In [3]:
import numpy as np
from numpy.linalg import norm


## методичка 1

### задание 1

а) произведение неопределено число строк не = количеству столбцов
б) не определено 2х5 ; 5х3 ; 2 не = 3
в) 8х8
г) 4х4

### задание 2

In [8]:
a = np.array([[1, -2],[3,0]])

b = np.array([[4, 1],[0,5]])

c=a+b
print(c)  

[[ 5 -1]
 [ 3  5]]


In [9]:
c2 = a@b
print (c2)

[[ 4 -9]
 [12  3]]


### задание 3

In [13]:
A = np.array([[1, 7],[3,-6]])

B = np.array([[0, 5],[2,-1]])

C = np.array([[2, -4],[1,1]])

D = 3*A - 2*B + 4*C
D





array([[ 11,  -5],
       [  9, -12]])

### задание 4

In [12]:
A = np.array([[4, 1],[5,-2], [2,3]])
A_T = A.T
A_T



array([[ 4,  5,  2],
       [ 1, -2,  3]])

In [14]:
AA_T = A@A_T
AA_T

array([[ 11,  -9,  23],
       [  6,  27, -12]])

In [15]:
# A_TA = A_T@A
произведение не определено

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 2 is different from 3)